{% set name = "pyiapws95" %}
{% set version = "0.1.0" %}
{% set build_number = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  # name: "pyiapws95"
  # version: "0.1.0"

source:
  git_url: {{ "https://github.com/yt87/pyiapws95.git" }}

build:
  noarch: python
  number: {{ build_number }}
  script: python setup.py install

requirements:
  host:
    - python # {{ python }}
    - numpy >=1.18
    - setuptools <50.0
  run:
    - python
    - numpy

test:
  imports:
    - pyiapws95

about:
  home: https://github.com/yt87/pyiapws95
  license: BSD-0-Clause
  license_family: BSD
  license_file: LICENCE
  summary: Python package to compute thermodynamic properties of water.

extra:
  recipe-maintainers:
    - yt87
